<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CakeBudget</title>

    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">

    <!-- Scripts -->
    <!--[if lt IE 9]><script type="text/javascript" src="/js/html5shiv.js"></script><![endif]-->
    <!--[if lt IE 9]><script type="text/javascript" src="/js/respond.min.js"></script><![endif]-->
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="container">
    <h1>CakeBudget</h1>

  <hr>

  <footer>
    <p>Deverá ser um template com AngularJS</p>
  </footer>
  </div>
</body>
</html>